# shared/dto/use_case_errors.py
from enum import Enum


class FabbankError(Enum):
    GENERIC_ERROR = "FABBANK_GENERIC_ERROR"
    WALLET_NOT_FOUND = "FABBANK_WALLET_NOT_FOUND"
    INSUFFICIENT_BALANCE = "FABBANK_INSUFFICIENT_BALANCE"
    TRANSFER_TARGET_USER_NOT_FOUND = "FABBANK_TRANSFER_TARGET_USER_NOT_FOUND"
    TRANSFER_GENERIC_ERROR = "FABBANK_TRANSFER_GENERIC_ERROR"
    TRANSFER_WRONG_PARAMS = "FABBANK_TRANSFER_WRONG_PARAMS"
    TRANSFER_PERMISSION_DENIED = "FABBANK_TRANSFER_PERMISSION_DENIED"
    LOJA_NO_ITEMS = "FABBANK_LOJA_NO_ITEMS"
    LOJA_ITEM_UNAVAILABLE = "FABBANK_LOJA_ITEM_UNAVAILABLE"
    LOJA_ITEM_PRICE_CHANGED = "FABBANK_LOJA_ITEM_PRICE_CHANGED"
    LOJA_BUY_ERROR = "FABBANK_LOJA_BUY_ERROR"


class FabzendaError(Enum):
    ANIMAL_NOT_FOUND = "FABZENDA_ANIMAL_NOT_FOUND"
    MAX_ANIMALS_REACHED = "FABZENDA_MAX_ANIMALS_REACHED"
    INSUFFICIENT_BALANCE = "FABZENDA_INSUFFICIENT_BALANCE"  # Pode ser genérico ou específico
    WALLET_NOT_FOUND = "FABZENDA_WALLET_NOT_FOUND"
    STORE_ITEM_NOT_AVAILABLE = "FABZENDA_STORE_ITEM_NOT_AVAILABLE"
    STORE_TRANSACTION_ERROR = "FABZENDA_STORE_TRANSACTION_ERROR"
    STORE_BUY_ERROR = "FABZENDA_STORE_BUY_ERROR"
    CELEIRO_ANIMAL_TYPE_NOT_AVAILABLE = "FABZENDA_CELEIRO_ANIMAL_TYPE_NOT_AVAILABLE"
    CELEIRO_TRANSACTION_ERROR = "FABZENDA_CELEIRO_TRANSACTION_ERROR"
    CELEIRO_CREATED_ERROR = "FABZENDA_CELEIRO_CREATED_ERROR"
    FEED_ANIMAL_DEAD = "FABZENDA_FEED_ANIMAL_DEAD"
    FEED_TRANSACTION_ERROR = "FABZENDA_FEED_TRANSACTION_ERROR"
    FEED_ERROR = "FABZENDA_FEED_ERROR"
    BURIAL_ANIMAL_LIVES = "FABZENDA_BURIAL_ANIMAL_LIVES"
    BURIAL_TRANSACTION_ERROR = "FABZENDA_BURIAL_TRANSACTION_ERROR"
    BURIAL_ERROR = "FABZENDA_BURIAL_ERROR"
    ABDUCTION_ANIMAL_LIVES = "FABZENDA_ABDUCTION_ANIMAL_LIVES"
    ABDUCTION_TRANSACTION_ERROR = "FABZENDA_ABDUCTION_TRANSACTION_ERROR"
    ABDUCTION_ERROR = "FABZENDA_ABDUCTION_ERROR"
    # Adicione outros erros específicos da Fabzenda


class GenericError(Enum):
    VALIDATION_ERROR = "GENERIC_VALIDATION_ERROR"
    UNAUTHORIZED = "GENERIC_UNAUTHORIZED"
    COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND"
    UNKNOWN_ERROR = "GENERIC_UNKNOWN_ERROR"


ErrorCode = FabbankError | FabzendaError | GenericError | None
