from enum import Enum


class FabbankUseCaseCode(Enum):
    OPTION_LOJA = "FABBANK_OPTION_LOJA"
    SALDO = "FABBANK_SALDO"
    TRANSFERENCIA = "FABBANK_TRANSFERENCIA"
    LOJA = "FABBANK_LOJA"
    LOJA_COMPRAR_ITEM = "FABBANK_LOJA_COMPRAR_ITEM"
    ALTERAR_SALDO = "FABBANK_ALTERAR_SALDO"


class FabzendaUseCaseCode(Enum):
    OPTION = "FABZENDA_OPTION"
    VER_FAZENDA = "FABZENDA_VER_FAZENDA"
    VER_CELEIRO = "FABZENDA_VER_CELEIRO"
    VER_STORE = "FABZENDA_VER_STORE"
    FAZENDA_DETALHE_ANIMAL = "FABZENDA_DETALHE_ANIMAL"
    ENTERRAR_ANIMAL = "FABZENDA_ENTERRAR_ANIMAL"
    ALIMENTAR_ANIMAL = "FABZENDA_ALIMENTAR_ANIMAL"
    ABDUZIR_ANIMAL = "FABZENDA_ABDUZIR_ANIMAL"
    CELEIRO_DETALHE_ANIMAL = "FABZENDA_CELEIRO_DETALHE_ANIMAL"
    CELEIRO_COMPRAR_ANIMAL = "FABZENDA_COMPRAR_ANIMAL"
    STORE_COMPRAR_ITEM = "FABZENDA_STORE_COMPRAR_ITEM"
    STORE_DETALHE_ITEM = "FABZENDA_STORE_DETALHE_ITEM"


class DebriefingUseCaseCode(Enum):
    NOTIFICAR = "DEBRIEFING_NOTIFICAR"
    VALIDAR = "DEBRIEFING_VALIDAR"


UseCaseCode = FabbankUseCaseCode | FabzendaUseCaseCode | DebriefingUseCaseCode | None
