from enum import Enum


class FabzendaHints(Enum):
    FAZENDA_OVERVIEW_VAZIA = 10
    FAZENDA_OVERVIEW = 11
    FAZENDA_OVERVIEW_DETALHE_ANIMAL = 12
    FAZENDA_ERROR = 13

    CELEIRO_OVERVIEW = 20
    CELEIRO_DETALHE_ANIMAL = 21
    CELEIRO_MAX_ANIMALS_REACHED = 22
    CELEIRO_INSUFFICIENT_BALANCE = 23
    CELEIRO_ANIMAL_TYPE_NOT_AVAILABLE = 24
    CELEIRO_TRANSACTION_ERROR = 25
    CELEIRO_CREATED_ERROR = 26
    CELEIRO_WALLET_NOT_FOUND = 27
    CELEIRO_ANIMAL_BUY_SUCCESS = 28

    FEED_INSUFFICIENT_BALANCE = 30
    FEED_ANIMAL_DEAD = 31
    FEED_TRANSACTION_ERROR = 32
    FEED_ERROR = 33
    FEED_SUCCESS = 34

    BURIAL_INSUFFICIENT_BALANCE = 40
    BURIAL_ANIMAL_LIVES = 41
    BURIAL_TRANSACTION_ERROR = 42
    BURIAL_ERROR = 43
    BURIAL_SUCCESS = 44

    ABDUCTION_ANIMAL_LIVES = 50
    ABDUCTION_TRANSACTION_ERROR = 51
    ABDUCTION_ERROR = 52
    ABDUCTION_SUCCESS = 53
