from enum import Enum


class FabbankHints(Enum):
    BALANCE = 10
    BALANCE_ADMIN = 11
    BALANCE_WALLET_NOT_FOUND = 12

    TRANSFER_SUCCESS = 20
    TRANSFER_SUCCESS_NOTIFICATION = 21
    TRANSFER_WRONG_PARAMS = 22
    TRANSFER_WALLET_NOT_FOUND = 23
    TRANSFER_INSUFFICIENT_BALANCE = 24
    TRANSFER_PERMISSION_DENIED = 25
    TRANSFER_ERROR = 26

    LOJA_OVERVIEW = 30
    LOJA_NO_ITEMS = 31
    LOJA_ITEM_UNAVAILABLE = 32
    LOJA_WALLET_NOT_FOUND = 33
    LOJA_INSUFFICIENT_BALANCE = 34
    LOJA_ITEM_PRICE_CHANGED = 35
    LOJA_BUY_SUCCESS = 36
    LOJA_BUY_ERROR = 37
    LOJA_BUY_ADMIN = 38
    LOJA_OPTIONS = 39


class FabzendaHints(Enum):
    FAZENDA_OPTIONS = 0
    FAZENDA_OVERVIEW_VAZIA = 10
    FAZENDA_OVERVIEW = 11
    FAZENDA_OVERVIEW_DETALHE_ANIMAL = 12
    FAZENDA_ERROR = 13
    FAZENDA_NOT_FOUND = 14

    CELEIRO_OVERVIEW = 20
    CELEIRO_DETALHE_ANIMAL = 21
    CELEIRO_MAX_ANIMALS_REACHED = 22
    CELEIRO_INSUFFICIENT_BALANCE = 23
    CELEIRO_ANIMAL_TYPE_NOT_AVAILABLE = 24
    CELEIRO_TRANSACTION_ERROR = 25
    CELEIRO_CREATED_ERROR = 26
    CELEIRO_WALLET_NOT_FOUND = 27
    CELEIRO_ANIMAL_BUY_SUCCESS = 28

    FEED_INSUFFICIENT_BALANCE = 30
    FEED_ANIMAL_DEAD = 31
    FEED_TRANSACTION_ERROR = 32
    FEED_ERROR = 33
    FEED_SUCCESS = 34

    BURIAL_INSUFFICIENT_BALANCE = 40
    BURIAL_ANIMAL_LIVES = 41
    BURIAL_TRANSACTION_ERROR = 42
    BURIAL_ERROR = 43
    BURIAL_SUCCESS = 44

    ABDUCTION_ANIMAL_LIVES = 50
    ABDUCTION_TRANSACTION_ERROR = 51
    ABDUCTION_ERROR = 52
    ABDUCTION_SUCCESS = 53

    NOTIFICATE_ANIMAL_SICK = 60
    NOTIFICATE_ANIMAL_DEAD = 61
    NOTIFICATE_CHANNEL_ANIMAL_DEAD = 62
    NOTIFICATE_ANIMAL_ABDUCTED = 63

    NOTIFICATE_CHANNEL_LOTTERY = 70
    NOTIFICATE_LOTTERY = 71
