"""Itens fabzenda

Revision ID: 581bca0205f6
Revises: b169e1c8fd50
Create Date: 2025-04-24 12:02:23.653721

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "581bca0205f6"
down_revision: str | None = "b169e1c8fd50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_definitions",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("emoji", sa.String(length=5), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "item_target",
            sa.Enum("ANIMAL", "FARM", name="item_target_enum", schema="fabzenda"),
            server_default=sa.text("'ANIMAL'"),
            nullable=False,
        ),
        sa.Column(
            "effect_type",
            sa.Enum("CONSUMABLE", "EQUIP", name="effect_type_enum", schema="fabzenda"),
            server_default=sa.text("'CONSUMABLE'"),
            nullable=False,
        ),
        sa.Column("effect", sa.JSON(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("item_id"),
        schema="fabzenda",
    )
    op.create_table(
        "inventory_items",
        sa.Column("inventory_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_animal_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["fabzenda.item_definitions.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_animal_id"],
            ["fabzenda.user_animals.animal_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("inventory_id"),
        schema="fabzenda",
    )

    seed_item_definitions = sa.text("""
        INSERT INTO fabzenda.item_definitions (item_id, name, emoji, price, description, item_target, effect_type, effect, duration, available)
        VALUES
        (1, 'Potinho', '🫙', 50, 'Um potinho mágico usado para guardar os seres mais fofos do planeta', 'FARM', 'EQUIP', '{"ADD_SLOT_FARM": 1}', NULL, true),
        (2, 'Chapeuzin', '👒', 7, 'Um chapeu gourmet que deixa seu fabicho mais estiloso e valioso', 'ANIMAL', 'EQUIP', '{"REWARD_MULT": 0.5}', NULL, true),
        (3, 'Normalizador', '🧼', 10, 'Um poderoso desinfetante que limpa todo e qualquer modificador', 'ANIMAL', 'CONSUMABLE', '{"CHANGE_MODIFIER": 0}', NULL, true),
        (4, 'Bolsa Térmica', '🎒', 20, 'Um lugar geladinho para guardar temporariamente seus fabichinhos', 'FARM', 'CONSUMABLE', '{"ADD_EXPIRE_DAY": 15, "ADD_HUNGER_DAY": 15}', NULL, true);
                                
        ALTER SEQUENCE fabzenda.item_definitions_item_id_seq RESTART WITH 5;
    """)
    op.execute(seed_item_definitions)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory_items", schema="fabzenda")
    op.drop_table("item_definitions", schema="fabzenda")
    op.execute(sa.text('DROP TYPE fabzenda.effect_type_enum";'))
    op.execute(sa.text('DROP TYPE fabzenda.item_target_enum";'))
    # ### end Alembic commands ###
